baseURL = "https://sundonghui0317.github.io/h.github.io/"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "∞"
disqusShortname = "disqus-code"
googleAnalytics = "analytics-code"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    search = "search"
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubLink = ""

    tagsInHome = 40     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "主页"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "博客"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "标签"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "章节"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "帖子"
                url = "/posts/"
                weight = 3

    [[menu.main]]
        name = "关于我"
        url = "/author/"
        weight = 3